language: php

php:
 - 7.0.15

branches:
 - master

before_script:
 - cd /home/travis/build/
 - phpenv config-rm xdebug.ini
 - pecl install channel://pecl.php.net/pthreads-3.1.6
 - pecl install channel://pecl.php.net/weakref-0.3.3
 - echo | pecl install channel://pecl.php.net/yaml-2.0.0
 - git clone --recursive --depth=50 --branch=master https://github.com/pmmp/PocketMine-MP.git
 - mkdir -p PocketMine-MP/plugins/KaiAuth-src
 - cp -rf KairusDarkSeeker/KaiAuth/src PocketMine-MP/plugins/KaiAuth-src
 - cp -rf KairusDarkSeeker/KaiAuth/resources PocketMine-MP/plugins/KaiAuth-src
 - cp -rf KairusDarkSeeker/KaiAuth/plugin.yml PocketMine-MP/plugins/KaiAuth-src
 - cp -rf KairusDarkSeeker/KaiAuth/LICENSE PocketMine-MP/plugins/KaiAuth-src
 - cp -rf KairusDarkSeeker/KaiAuth/build.php PocketMine-MP/
 - git clone https://github.com/pmmp/PocketMine-DevTools.git
 - cp KairusDarkSeeker/KaiAuth/compiledevtools.php /home/travis/build/
 - php compiledevtools.php
 - cd PocketMine-MP/

script:
 - php build.php

deploy:
  provider: releases
  api_key: "$api_key"
  file: "/home/travis/build/PocketMine-MP/plugins/DevTools/KaiAuth.phar"
  skip_cleanup: true
  overwrite: true
  on:
    tags: false

notifications:
 email: false
