name: KaiAuth
main: kairusds\kaiauth\Main
version: 0.1.0
api:
- 3.0.0
- 3.0.0-ALPHA1
- 3.0.0-ALPHA2
- 3.0.0-ALPHA3
- 3.0.0-ALPHA4
- 3.0.0-ALPHA5
- 3.0.0-ALPHA6
author: KairusDarkSeeker
website: https://twitter.com/kairusds

commands:
  login:
    description: "login to your account"
  register:
    description: "register for an account"
  chpwd:
    description: "change your account's password"
  unregister:
    description: "disband your account"
